### ISSUE TITLE
150GB vs 50GB

### ISSUE THREAD

**Issue by dangelov** [scaleway-community/scaleway-webmin#9]
I opened a ticket about this and was advised to open an issue here instead.

It would seem that this image was updated to use 50GB volumes, judging by a closed pull request on this repo, but trying to create a new server via the Scaleway control panel defaults to [150GB](http://dew.dangelov.com/dewdrops/DEW-5819fcaddd96b9.92904849.png).

**Comment by QuentinPerez** [comment]
Hi @dangelov,

The images have `50GB` to be supported on `VC1S`. You can create your own webmin image with the following instructions `https://github.com/scaleway/image-builder` (just change the size in the `Makefile`).

**Comment by dangelov** [comment]
Sorry, I think my initial report was a bit unclear. I actually want a 50GB image/volume, but every time I select "Webmin", it automatically switches to 150GB, which I don't want.

**Comment by QuentinPerez** [comment]
Oups sorry, I will release a new version

**Comment by dangelov** [comment]
@QuentinPerez Thanks for your time. Not sure if you were able to release it, but if you did, this still seems to be an issue when trying to create an image through ScaleWay's control panel.

**Comment by QuentinPerez** [comment]
Hi @dangelov, sorry for the delayed release, but it's available now.

**Comment by dangelov** [comment]
Perfect, seems to be working nicely now. Thank you for your time!
